stages:
  - pre-verify
  - test
  - build
  - post-verify
  - deploy

verifySettings:
  stage: pre-verify
  tags:
    - rasp-ci
  script:
    - chmod a+x ./CI/verify.sh
    - ./CI/verify.sh

verifyFolders:
  stage: pre-verify
  tags:
    - rasp-ci
  script:
    - chmod a+x ./CI/verifystruct.sh
    - ./CI/verifystruct.sh

buildRemoteAndroid:
  image: "gableroux/unity3d:2018.1.2f1-android"
  tags: 
    - shared
    - linux
  stage: build
  allow_failure: true
  before_script: 
    - chmod a+x ./CI/unity-before-script.sh && ./CI/unity-before-script.sh
  script:
    - chmod a+x ./CI/build.sh
    - ./CI/build.sh
  artifacts:
    paths:
    - ./Builds/
  only:
    - master

buildLocalAndroid:
  tags: 
    - VR-Win
  stage: build
  script:
    - set PATH=%PATH%;F:\Apps\Game-App Development\Unity 2018.1.1f3x64\Editor
    - .\CI\buildLocal.bat
  artifacts:
    paths:
    - ./Builds/
  only:
    - master